language: node_js

sudo: false

branches:
  only:
  - blog-source

cache:
  - npm

node_js: stable
  # - "14"

before_script:
  - npm install
  - hexo cl

script:
  - hexo clean
  - hexo generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  keep-history: true
  target_branch: master
  on:
    branch: blog-source