# Menu
menu:
  Home: /
  Archives: /archives
  # Gallery: /gallery
  Categories: /categories
  Tags: /tags
  About: /about
rss: /atom.xml


# Miscellaneous
favicon: /favicon.ico
brand: /images/volleyball_black.svg

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: /images/ocean/
  brand: /images/volleyball_inverted.png

# Content
excerpt_link: Read More

# # MIIT ICP/IP/DOMAIN
# beian:
#   enable: false
#   number: 京ICP备17054916号-2
#   url: https://.miit.gov.cn/

# Tags
show_count: false

# Toc
toc: true

# fancybox
fancybox: true

# Local search
search_text: Search

# 是否显示复制按钮
show_copy_btn: true

# Gitalk
gitalk:
  enable: false # true
  clientID: # GitHub Application Client ID
  clientSecret: # Client Secret
  repo: # Repository name
  owner: # GitHub ID
  admin: # GitHub ID

# Valine
valine:
  enable: false # true
  el: 'vcomments'
  appId:
  appKey:
  notify: false
  verify: true
  avatar: 'mp'
  pageSize: '10'
  placeholder: '請輸入...'

# MathJax Support
mathjax:
  enable: true
  per_page: true
  # cdn: https://cdn.jsdelivr.net/npm/mathjax@2.7.8/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  cdn: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  # cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
